//! Naming rules shared with php-src `build/gen_stub.php`.

const std = @import("std");

/// Convert a canonical PHP qualified name to gen_stub's declaration fragment.
///
/// gen_stub applies `implode("_", $name->getParts())`: namespace separators
/// become underscores, while case and underscores inside each part are kept.
pub fn declarationName(comptime qualified_name: [:0]const u8) [:0]const u8 {
    comptime var buffer: [qualified_name.len:0]u8 = undefined;
    inline for (qualified_name, 0..) |ch, i| {
        buffer[i] = if (ch == '\\') '_' else ch;
    }
    const result = buffer;
    return &result;
}

/// Name of the `zend_function_entry` table generated for a class with methods.
pub fn classMethodsSymbolName(comptime class_name: [:0]const u8) [:0]const u8 {
    return "class_" ++ comptime declarationName(class_name) ++ "_methods";
}

/// Name of the class registration function generated by gen_stub.
pub fn classRegisterFnSymbolName(comptime class_name: [:0]const u8) [:0]const u8 {
    return "register_class_" ++ comptime declarationName(class_name);
}

/// Handler symbol generated by `ZEND_FUNCTION`.
pub fn functionSymbolName(comptime function_name: [:0]const u8) [:0]const u8 {
    return "zif_" ++ comptime declarationName(function_name);
}

/// Handler symbol prefix generated by `ZEND_METHOD` for a class.
pub fn methodSymbolPrefix(comptime class_name: [:0]const u8) [:0]const u8 {
    return "zim_" ++ comptime declarationName(class_name) ++ "_";
}

/// Handler symbol generated by `ZEND_METHOD`.
pub fn methodSymbolName(comptime class_name: [:0]const u8, comptime method_name: [:0]const u8) [:0]const u8 {
    return comptime methodSymbolPrefix(class_name) ++ method_name;
}

test "match gen_stub declaration names" {
    try std.testing.expectEqualStrings("MyPHPExt_Counter", declarationName("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("class_MyPHPExt_Counter_methods", classMethodsSymbolName("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("register_class_MyPHPExt_Counter", classRegisterFnSymbolName("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("zif_MyPHPExt_hello", functionSymbolName("MyPHPExt\\hello"));
    try std.testing.expectEqualStrings("zim_MyPHPExt_Counter_", methodSymbolPrefix("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("zim_MyPHPExt_Counter___construct", methodSymbolName("MyPHPExt\\Counter", "__construct"));
}
