//! Compile-time declaration tables and naming rules shared with `gen_stub.php`.

const std = @import("std");

/// Stub-order metadata with enum lookups to avoid StaticStringMap's comptime cost.
pub fn DeclarationTable(comptime Value: type) type {
    return struct {
        const Self = @This();

        entries: []const Value,
        Name: type,

        /// Build from .{ name, value } pairs, e.g. .{ .{ "foo", value } }.
        pub fn initComptime(comptime pairs: anytype) Self {
            var field_names: [pairs.len][]const u8 = undefined;
            var entries: [pairs.len]Value = undefined;
            for (pairs, 0..) |pair, i| {
                field_names[i] = pair[0];
                entries[i] = pair[1];
            }
            const final_entries = entries;
            return .{
                .entries = &final_entries,
                .Name = if (pairs.len == 0) enum {} else @Enum(usize, .exhaustive, &field_names, &std.simd.iota(usize, pairs.len)),
            };
        }

        pub fn names(comptime self: Self) []const []const u8 {
            return @typeInfo(self.Name).@"enum".field_names;
        }

        pub fn getIndex(comptime self: Self, comptime name: []const u8) ?usize {
            if (!@hasField(self.Name, name)) return null;
            return @backingInt(@field(self.Name, name));
        }

        pub fn has(comptime self: Self, comptime name: []const u8) bool {
            return @hasField(self.Name, name);
        }
    };
}

/// Estimate 512 branches per declaration, plus Zig's default 1000.
pub fn declarationQuota(comptime count: usize) u32 {
    return @intCast(1_000 + count * 512);
}

/// Convert a canonical PHP qualified name to gen_stub's declaration fragment.
///
/// gen_stub applies `implode("_", $name->getParts())`: namespace separators
/// become underscores, while case and underscores inside each part are kept.
pub fn declarationName(comptime qualified_name: [:0]const u8) [:0]const u8 {
    comptime var buffer: [qualified_name.len:0]u8 = undefined;
    inline for (qualified_name, 0..) |ch, i| {
        buffer[i] = if (ch == '\\') '_' else ch;
    }
    const result = buffer;
    return &result;
}

/// Name of the `zend_function_entry` table generated for a class with methods.
pub fn classMethodsSymbolName(comptime class_name: [:0]const u8) [:0]const u8 {
    return "class_" ++ comptime declarationName(class_name) ++ "_methods";
}

/// Name of the class registration function generated by gen_stub.
pub fn classRegisterFnSymbolName(comptime class_name: [:0]const u8) [:0]const u8 {
    return "register_class_" ++ comptime declarationName(class_name);
}

/// Handler symbol generated by `ZEND_FUNCTION`.
pub fn functionSymbolName(comptime function_name: [:0]const u8) [:0]const u8 {
    return "zif_" ++ comptime declarationName(function_name);
}

/// Handler symbol prefix generated by `ZEND_METHOD` for a class.
pub fn methodSymbolPrefix(comptime class_name: [:0]const u8) [:0]const u8 {
    return "zim_" ++ comptime declarationName(class_name) ++ "_";
}

/// Handler symbol generated by `ZEND_METHOD`.
pub fn methodSymbolName(comptime class_name: [:0]const u8, comptime method_name: [:0]const u8) [:0]const u8 {
    return comptime methodSymbolPrefix(class_name) ++ method_name;
}

test "match gen_stub declaration names" {
    try std.testing.expectEqualStrings("MyPHPExt_Counter", declarationName("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("class_MyPHPExt_Counter_methods", classMethodsSymbolName("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("register_class_MyPHPExt_Counter", classRegisterFnSymbolName("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("zif_MyPHPExt_hello", functionSymbolName("MyPHPExt\\hello"));
    try std.testing.expectEqualStrings("zim_MyPHPExt_Counter_", methodSymbolPrefix("MyPHPExt\\Counter"));
    try std.testing.expectEqualStrings("zim_MyPHPExt_Counter___construct", methodSymbolName("MyPHPExt\\Counter", "__construct"));
}
