name: Test

on:
  push:
    branches: ["dev"]
    paths:
      - "src/**"
      - "build.zig"
      - "build.zig.zon"
      - ".github/workflows/test.yml"
  pull_request:
    branches: ["dev"]
    paths:
      - "src/**"
      - "build.zig"
      - "build.zig.zon"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - name: Install PHP development headers
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: php-dev
          version: 1.0
      - name: Run tests
        run: |
          PHP_INCLUDE_DIR=$(php-config --include-dir)
          zig build test -Dphp-include-root="$PHP_INCLUDE_DIR"
